docker buildx
build --file Dockerfile
--cache-from type=gha --cache-to type=gha,mode=max --iidfile /tmp/docker-actions-toolkit-ZaA58L/iidfile --tag ghcr.io/bishwajeetbarnwal/spring-boot-application:pr-2 --push .
